# Generated by Django 4.1.5 on 2023-01-11 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_healthy',
        ),
    ]
