# Generated by Django 4.1.5 on 2023-01-07 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_healthy",
            field=models.BooleanField(default=True),
        ),
    ]
