# Generated by Django 4.1.5 on 2023-01-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
