# Generated by Django 4.1.5 on 2023-01-06 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="user",
        ),
    ]
