# Generated by Django 4.1.5 on 2023-01-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("house bills", "House Bills"),
                    ("leisure", "Leisure"),
                    ("education", "Education"),
                    ("investment", "Investment"),
                    ("health", "Health"),
                    ("travel", "Travel"),
                    ("self_care", "Self Care"),
                    ("clothes", "Clothes"),
                    ("cashin", "Cashin"),
                    ("transportation", "Transportation"),
                    ("food", "Food"),
                    ("donation", "Donation"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
