# Generated by Django 4.1.5 on 2023-01-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="transactions_value",
        ),
    ]
